name: 🧪 SDK Extension Testing

on: [push, pull_request, workflow_dispatch]

env: ${{ secrets }}

jobs:

  GuildsManager:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v2
      
    - name: Install dependencies
      run: npm install
    
    - name: get method
      working-directory: tests/guilds-manager
      run: jest get
      
    - name: post method
      working-directory: tests/guilds-manager
      run: jest post
      
    - name: delete method
      working-directory: tests/guilds-manager
      run: jest delete
      
    - name: fetch method
      working-directory: tests/guilds-manager
      run: jest fetch
